### PR TITLE
Fix cover not working

### PR DESCRIPTION
**Pull request by mulgaBrian**
Adds the necessary settings for wkhtmltopdf.dll to add the cover page.
To remove the margins you need to update wkhtmltopdf.dll itself with the fix margins pr.
I have tested with the original and my own modified wkhtmltopdf dll.

### CODE REVIEW

**Comment by HakanL** [comment]
Looks good, thanks for contributing! Have you submitted a PR to the native/parent project as well to change the margin?

**Comment by mulgaBrian** [comment]
The wkhtmltopdf project is archived.
I used https://github.com/wkhtmltopdf/wkhtmltopdf/pull/5193 and built my own dll to replace the one in this project.

**Comment by HakanL** [comment]
Yeah that's what I thought as well. What is the purpose of removing the margins, is there a report issue about that?

**Comment by mulgaBrian** [comment]
I build and use an image to make the cover page which, when un-patched leaves the margins as a white area around the image. After the patch the image covers the whole page.

**Comment by HakanL** [comment]
I see, and I assume that issue is also when using the native command-line wkhtml tool, so it's strictly in that library? Sometimes I wonder if it would be worth the effort to fork the native library, upgrade it to use a newer version of libssl. But I think they're using a version of QT that is very old, so it may be hard to get everything running (for cross-compiling). And I'm not sure I'm the right person to maintain that project either.

**Comment by mulgaBrian** [comment]
I am building the wkhtmltopdf project myself to produce the dll and exe. It has problems with the vagrant windows builds that I haven't been able to fix yet so I use the mxe-cross builds to get them. This works best for me on older versions of Ubuntu which have the gcc7 compilers.
The Qt version 4 is the last open source version so the Qt section cannot be updated.
I am also building this/your project myself to use the updated wkhtmltopdf binaries.

**Comment by HakanL** [comment]
Yeah, it would be an undertaking to set up a build environment for all supported environments of the binaries, locked down to the older versions of dependencies where needed. I guess it could be done in a docker environment where the older version of gcc could be used, etc.

**Pull request merged**
